### DISCUSSION TITLE
Format of configuration file

### DISCUSSION THREAD

**Discussion by christophe-david** [fast-aircraft-design/FAST-OAD#213] [Ideas]
FAST-OAD usage has shown that the current format for configuration file could maybe be enhanced.
As some other configuration information will come, in this file or another (beginning with the descriptions of sizing and operational missions), it is probably a good time for thinking this format again.

To begin with, here is a sample file:
```toml
title = "Current FAST-OAD format"

# List of folder paths where user added custom registered OpenMDAO components
module_folders = ["my/folder", "some/other/folder"]

# Input and output files
input_file = "./problem_inputs.xml"
output_file = "./problem_outputs.xml"

# Definition of problem driver assuming the OpenMDAO convention "import openmdao.api as om"
driver = "om.ScipyOptimizeDriver(tol=1e-6, optimizer='COBYLA')"


# Definition of OpenMDAO model
[model]
# Solvers are defined assuming the OpenMDAO convention "import openmdao.api as om"
    nonlinear_solver = "om.NonlinearBlockGS(maxiter=200)"
    linear_solver = "om.DirectSolver()"

    # Although "model" is a mandatory name for the top level of the model, its
    # sub-components can be freely named by user
    [model.my_first_model]
        # An OpenMDAO component is identified by its "id"
        id = "my.first.model"
    [model.my_group]
        [model.my_group.my_second_model]
            id = "my.second.model"
        [model.my_group.my_third_model]
            id = "my.third.model"
            some_model_option = 11



[optimization]  # Actually, this line can be omitted
# This section is needed only if optimization process is run

    # Double brackets are needed when using multiple occurences of the same key
    [[optimization.design_var]]
        name = "first:design_var"
        lower = 0.0
        upper = 42.0
    [[optimization.design_var]]
        name = "second:design_var"
        lower = -100.0
        upper = 0.0

    [[optimization.constraint]]
        name = "first:constraint"
        lower = 0.05
        upper = 0.1
    [[optimization.constraint]]
        name = "second:constraint"
        lower = -1.5
        upper = 1.0   # TOML format does not accept "1."

    [[optimization.objective]]
        name = "one:objective:function"
```

Here are some problems I saw in relation with current formatting (please feel free:
1. There is a mix of keys that can be named by user (model names, group names) and keys that have fixed names ("model", "design_var", ...)
1. There is a mix of simple and double brackets that is part of TOML syntax, but that can be confusing for users.
1. Nested structures require to repeat the name of parent structure (e.g. **`model`**`.my_first_model`)
1. TOML format does not support floats that end with a dot: `1.0` is Ok, but `1.` is not.

Some modifications of current format could be implemented to fix some of these problems. For instance, even if it is not required by TOML syntax, we could decide that double-bracketed keys have fixed name, whereas simple-bracketed keys are free to name. Also, as design variables, constraints and objective are obviously related to optimization, the "optimization" key might be removed.
That would give:
```toml
title = "Possible alternative to current format"

# List of folder paths where user added custom registered OpenMDAO components
module_folders = ["my/folder", "some/other/folder"]

# Input and output files
input_file = "./problem_inputs.xml"
output_file = "./problem_outputs.xml"

# Definition of problem driver assuming the OpenMDAO convention "import openmdao.api as om"
driver = "om.ScipyOptimizeDriver(tol=1e-6, optimizer='COBYLA')"


# Definition of OpenMDAO model
[[model]]
# Solvers are defined assuming the OpenMDAO convention "import openmdao.api as om"
    nonlinear_solver = "om.NonlinearBlockGS(maxiter=200)"
    linear_solver = "om.DirectSolver()"

    # Although "model" is a mandatory name for the top level of the model, its
    # sub-components can be freely named by user
    [model.my_first_model]
        # An OpenMDAO component is identified by its "id"
        id = "my.first.model"
    [model.my_group]
        [model.my_group.my_second_model]
            id = "my.second.model"
        [model.my_group.my_third_model]
            id = "my.third.model"
            some_model_option = 11


# Optimization settings
[[design_var]]
    name = "first:design_var"
    lower = 0.0
    upper = 42.0
[[design_var]]
    name = "second:design_var"
    lower = -100.0
    upper = 0.0

[[constraint]]
    name = "first:constraint"
    lower = 0.05
    upper = 0.1
[[constraint]]
    name = "second:constraint"
    lower = -1.5
    upper = 1.0

[[objective]]
    name = "one:objective:function"
```

Another way might be to change to YAML, which is also a popular format. Unlike TOML, indentation is part of YAML syntax. A sample file could be:
```yaml
title: YAML alternative
module_folders: [ my/folder, some/other/folder ]

# Input and output files
input_file: ./problem_inputs.xml
output_file: ./problem_outputs.xml

# Definition of problem driver assuming the OpenMDAO convention import openmdao.api as om
driver: om.ScipyOptimizeDriver(tol:1e-6, optimizer:'COBYLA')

# Definition of OpenMDAO model
model_settings:
  # Solvers are defined assuming the OpenMDAO convention import openmdao.api as om
  nonlinear_solver: om.NonlinearBlockGS(maxiter:200)
  linear_solver: om.DirectSolver()

model:
  # Although "model" is a mandatory name for the top level of the model, its
  # sub-components can be freely named by user
  my_first_model:
    id: my.first.model
  my_group:
    my_second_model:
      id: my.second.model
    my_third_model:
      id: my.third.model
      some_model_option: 11


# This section is needed only if optimization process is run
optimization:
  design_vars:
    - name: first:design_var
      lower: 0.0
      upper: 42.0
    - name: second:design_var
      lower: -100.0
      upper: 0.0

  constraints:
    - name: first:constraint
      lower: 0.05
      upper: 0.1
    - name: second:constraint
      lower: -1.5
      upper: 1.

  objective: one:objective:function
```

I like some features of YAML:
- indentation decides what is nested in what --> no need to repeat parent name
- strings do not need to be quoted
- `1.` is accepted

On the other side, I fear that some user may break indentations by accidentally adding/removing some space. (although such problems may be identified at runtime using schema validation...)

What do you think? Any opinion is welcome !

**Comment by relf** [comment]
I discovered toml with FAST-OAD and was always wondering why did you pick it over yaml.  :wink: 
Regarding indentation breaking, I would add that typical FAST-OAD user should know a bit about Python and so should not be troubled by "significant indentation" syntax.

**Comment by ScottDelbecq** [comment]
What I do not like with the .toml is that the parser does not keep the ordering  even with [tomlkit](https://github.com/sdispater/tomlkit). It seems that it is possible with .yaml.

**Comment by christophe-david** [comment]
> I discovered toml with FAST-OAD and was always wondering why did you pick it over yaml. 😉
> Regarding indentation breaking, I would add that typical FAST-OAD user should know a bit about Python and so should not be troubled by "significant indentation" syntax.

I am not so sure about that. I hope that someday non-Python specialist would use FAST-OAD through command line, using the embedded models or custom models developed by others.

And even as a Python coder but while I was a YAML noob, I have been surprised by YAML indentation:
```yaml
foo:
  - bar:
      baz: 0
```
is not the same as:
```yaml
foo:
  - bar:
    baz: 0
```
but as I first thought that indentation had to be with respect to the dash sign, I did not understand the difference until I studied properly the YAML syntax.

Concerning the choice of TOML, the web is full of pros and cons for the 2 languages, but I would say I mostly followed the reasoning of [PEP518](https://www.python.org/dev/peps/pep-0518/#file-format) that defines the `pyproject.toml` file.
I still believe that for very simple file structures (like `pyproject.toml`), TOML is a good choice because it can be easily understood and modified without actually studying the TOML syntax.

But it appeared that FAST-OAD configuration needs a not-so-simple structure, and then TOML becomes too noisy and far less intuitive (beginning with the simple and double brackets thing).

Additionally, I found only recently [stricYAML](https://github.com/crdoconnor/strictyaml) that implements a subset of YAML and removed controversial YAML features, which looks well adapted to non-overly-complicated usage. I'll probably give it a try.
