### DISCUSSION TITLE
How to maximize re-usability of FAST-OAD "sub-models"

### DISCUSSION THREAD

**Discussion by christophe-david** [fast-aircraft-design/FAST-OAD#255] [Ideas]
##  Problem summary

FAST-OAD configuration file allows assembling any number of OpenMDAO components, as long as they are registered as FAST-OAD models, native or custom.

Currently, FAST-OAD proposes "high-level" models, that are dedicated to entire disciplines (geometry, mass, aerodynamics...) and some "link" models to add needed parts of computation loop.

Therefore, using an entirely new mass model is straight-forward, but what if user wants to write a custom model only for wing, for instance ?

## Details

Keeping the example of the model for wing mass, the problem is that registered mass model is an OpenMDAO group that contains a whole hierarchy of openMDAO systems, one of them being the one user wants to change.

Currently, user has no choice but copying all the OpenMDAO hierarchy above the component that needs to be replaced. For components at same hierarchy level, it would be possible to call the original FAST-OAD classes, but given that several parts required to be copied, user will logically not bother deciding what part can be imported and what other ones need to be copied: he will copy all.

On the contrary, the objective should be to encourage maximum usage of FAST-OAD code and custom modules should contain only specific code.

### Registering also lower-level models
FAST-OAD configuration file could build its process using lower-level models, allowing more flexibility.

It would not prevent to keep high-level models registered also.

```toml
[model]
    nonlinear_solver = "om.NonlinearBlockGS(maxiter=50)"
    linear_solver = "om.DirectSolver()"

    # sub-components can be freely named by user
    [model.geometry]
        id = "fastoad.geometry."
    [model.weight]
        [model.weight.payload]
            id = "fastoad.weight.payload_from_npax"
        [model.weight.owe]
            nonlinear_solver = "om.NonlinearBlockGS(maxiter=50, iprint=0)"
            linear_solver = "om.DirectSolver(iprint=0)"
            [model.weight.owe.propulsion]
                id = "custom.weight.propulsion"  # A custom module
            [model.weight.owe.airframe]
                [model.weight.owe.airframe.loads]
                    id = "fastoad.weight.airframe.loads"
                [model.weight.owe.airframe.wings]
                    id = "custom.weight.wings"  # A custom module
                [model.weight.owe.airframe.fuselage]
                    id = "fastoad.weight.airframe.fuselage"
                [model.weight.owe.airframe.empennage]
                    id = "fastoad.weight.airframe.empennage"
                [model.weight.owe.airframe.flight_controls]
                    id = "fastoad.weight.airframe.flight_controls"
                [model.weight.owe.airframe.landing_gears]
                    id = "fastoad.weight.airframe.landing_gears"
                [model.weight.owe.airframe.pylons]
                    id = "fastoad.weight.airframe.pylons"
                [model.weight.owe.airframe.paint]
                    id = "fastoad.weight.airframe.paint"
            [model.weight.owe.systems]
                id = "fastoad.weight.systems"
            [model.weight.owe.furniture]
                id = "fastoad.weight.furniture"
            [model.weight.owe.crew]
                id = "fastoad.weight.crew"
            [model.weight.owe.sum]
                id = "fastoad.weight.sum"
        [model.weight.mlw_mzfw]
            id = "fastoad.weight.legacy.mlw_mzfw"
    [model.mtow]
        id = "fastoad.mass_performances.link_MTOW"
    [model.aerodynamics_highspeed]
        id = "fastoad.aerodynamics.highspeed"
    [model.aerodynamics_lowspeed]
        id = "fastoad.aerodynamics.lowspeed"
    [model.aerodynamics_takeoff]
        id = "fastoad.aerodynamics.takeoff"
    [model.aerodynamics_landing]
        id = "fastoad.aerodynamics.landing"
        use_xfoil = false
    [model.performance]
        id = "fastoad.performances.breguet"
        propulsion_id = "fastoad.wrapper.propulsion.rubber_engine"
```

#### Pros
- Mechanics is already here. It only needs to register more OpenMDAO components.
- Should be adapted for almost all situations.

#### Cons
- Configuration file can become heavy.
- Group construction will be expected to mimic correctly the original group.
- Cannot work for "complex" groups (i.e. more than add_subsystem() and solver 
  settings)

### Dependency injection

Another solution would be to decide what part of models could be replaceable, and allow user to specify only its model.

```toml
[model]
    nonlinear_solver = "om.NonlinearBlockGS(maxiter=50)"
    linear_solver = "om.DirectSolver()"

    # sub-components can be freely named by user
    [model.geometry]
        id = "fastoad.geometry"
    [model.weight]
        id = "fastoad.weight"
        propulsion = "custom.weight.propulsion"
        wings = "custom.weight.airframe.wing"
    [model.mtow]
        id = "fastoad.mass_performances.link_MTOW"
    [model.aerodynamics_highspeed]
        id = "fastoad.aerodynamics.highspeed"
    [model.aerodynamics_lowspeed]
        id = "fastoad.aerodynamics.lowspeed"
    [model.aerodynamics_takeoff]
        id = "fastoad.aerodynamics.takeoff"
    [model.aerodynamics_landing]
        id = "fastoad.aerodynamics.landing"
        use_xfoil = false
    [model.performance]
        id = "fastoad.performances.breguet"
        propulsion_id = "fastoad.wrapper.propulsion.rubber_engine"
```

#### Pros
- Configuration file stays minimal.

#### Cons
- Modules that can be replaced have to be decided in FAST-OAD architecture.
- Some modifications needed in FAST-OAD

### "Library" of OpenMDAO systems

Python declaration:
```python
@SystemLibrary.register(service_name="service.weight.owe", system_id="fastoad.weight.owe")
class OperatingWeightEmpty(om.Group):
    """Operating Empty Weight (OEW) estimation.

    This group aggregates weight from all components of the aircraft.
    """

    def setup(self):
        self.add_subsystem(
            "propulsion_weight",
            SystemLibrary.get(service_name="service.weight.propulsion"),
            promotes=["*"],
        )
        self.add_subsystem(
            "airframe_weight",
            SystemLibrary.get(service_name="service.weight.airframe"),
            promotes=["*"],
        )
        self.add_subsystem(
            "systems_weight",
            SystemLibrary.get(service_name="service.weight.systems"),
            promotes=["*"],
        )
        self.add_subsystem(
            "furniture_weight",
            SystemLibrary.get(service_name="service.weight.furniture"),
            promotes=["*"],
        )
        self.add_subsystem(
            "crew_weight", SystemLibrary.get(service_name="service.weight.crew"), promotes=["*"]
        )

        self.add_subsystem(
            "OWE_sum", SystemLibrary.get(service_name="service.weight.owe_sum"), promotes=["*"]
        )


@SystemLibrary.register(service_name="service.weight.airframe", system_id="fastoad.weight.airframe")
class AirframeWeight(om.Group):
    """
    Computes mass of airframe.
    """

    def setup(self):
        SystemLibrary.add_subsystem(self, service_name="service.weight.airframe.loads")
        SystemLibrary.add_subsystem(self, service_name="service.weight.airframe.wings")
        SystemLibrary.add_subsystem(self, service_name="service.weight.airframe.fuselage")
        SystemLibrary.add_subsystem(self, service_name="service.weight.airframe.empennage")
        SystemLibrary.add_subsystem(self, service_name="service.weight.airframe.flight_controls")
        SystemLibrary.add_subsystem(self, service_name="service.weight.airframe.landing_gears")
        SystemLibrary.add_subsystem(self, service_name="service.weight.airframe.pylons")
        SystemLibrary.add_subsystem(self, service_name="service.weight.airframe.paint")
        SystemLibrary.add_subsystem(self, service_name="service.weight.airframe.sum")
```

Configuration file:
```toml
[model]
    nonlinear_solver = "om.NonlinearBlockGS(maxiter=50)"
    linear_solver = "om.DirectSolver()"

    # sub-components can be freely named by user
    [model.geometry]
        service_name = "service.geometry"
    [model.weight]
        service_name = "service.weight"
    [model.mtow]
        service_name = "service.mass_performances.link_MTOW"
    [model.aerodynamics_highspeed]
        service_name = "service.aerodynamics.highspeed"
    [model.aerodynamics_lowspeed]
        service_name = "service.aerodynamics.lowspeed"
    [model.aerodynamics_takeoff]
        service_name = "service.aerodynamics.takeoff"
    [model.aerodynamics_landing]
        service_name = "service.aerodynamics.landing"
    [model.performance]
        service_name = "service.performances.breguet"
        propulsion_id = "service.wrapper.propulsion.rubber_engine"

[service]
service.weight.airframe.wings = "custom.weight.mystran.wings"
service.weight.propulsion = "custom.weight.cfm-56"

```

#### Pros
- could allow model replacement at many levels
- configuration file would be kept simple

#### Cons
- Needs rewriting all existing FAST-OAD groups (after implementation of SystemLibrary)
