### ISSUE TITLE
listing variables shows "_auto_ivc.v*" variables

### ISSUE THREAD

**Issue by christophe-david** [fast-aircraft-design/FAST-OAD#225]
When using FAST-OAD with OpenMDAO 3.2+, the command `fastoad list_variables <my_conf>.toml` shows `_auto_ivc.v*` besides normal variables.
```toml
input_file = "./problem_inputs.xml"
output_file = "./problem_outputs.xml"

[model]
    [model.hq_static_margin]
        id = "fastoad.handling_qualities.static_margin"
```

```bash
$ fastoad list_variables foo.toml
- INPUTS OF THE PROBLEM -------------------------------------------------------------------------------------------
                   NAME                                                  DESCRIPTION

 data:aerodynamics:cruise:neutral_point:x  X-position of neutral point - X-position of aircraft nose

 data:weight:aircraft:CG:aft:MAC_position  most aft X-position of center of gravity as ratio of mean aerodynamic

                                           chord


- OUTPUTS OF THE PROBLEM ------------------------------------------------------------------------------------------
                   NAME                                                  DESCRIPTION

 _auto_ivc.v0

 _auto_ivc.v1

 data:handling_qualities:static_margin     (X-position of neutral point - X-position of center of gravity ) / (mean

                                           aerodynamic chord)

-------------------------------------------------------------------------------------------------------------------
```

BTW, it looks like the printed output has too many empy lines.
