### ISSUE TITLE
Current format for configuration file could be enhanced

### ISSUE THREAD

**Issue by christophe-david** [fast-aircraft-design/FAST-OAD#270]
FAST-OAD usage has shown that the current format for configuration file could maybe be enhanced.
As some other configuration information will come, in this file or another (beginning with the descriptions of sizing and operational missions), it is probably a good time for thinking this format again.

To begin with, here is a sample file:
```toml
title = "Current FAST-OAD format"

# List of folder paths where user added custom registered OpenMDAO components
module_folders = ["my/folder", "some/other/folder"]

# Input and output files
input_file = "./problem_inputs.xml"
output_file = "./problem_outputs.xml"

# Definition of problem driver assuming the OpenMDAO convention "import openmdao.api as om"
driver = "om.ScipyOptimizeDriver(tol=1e-6, optimizer='COBYLA')"


# Definition of OpenMDAO model
[model]
# Solvers are defined assuming the OpenMDAO convention "import openmdao.api as om"
    nonlinear_solver = "om.NonlinearBlockGS(maxiter=200)"
    linear_solver = "om.DirectSolver()"

    # Although "model" is a mandatory name for the top level of the model, its
    # sub-components can be freely named by user
    [model.my_first_model]
        # An OpenMDAO component is identified by its "id"
        id = "my.first.model"
    [model.my_group]
        [model.my_group.my_second_model]
            id = "my.second.model"
        [model.my_group.my_third_model]
            id = "my.third.model"
            some_model_option = 11



[optimization]  # Actually, this line can be omitted
# This section is needed only if optimization process is run

    # Double brackets are needed when using multiple occurences of the same key
    [[optimization.design_var]]
        name = "first:design_var"
        lower = 0.0
        upper = 42.0
    [[optimization.design_var]]
        name = "second:design_var"
        lower = -100.0
        upper = 0.0

    [[optimization.constraint]]
        name = "first:constraint"
        lower = 0.05
        upper = 0.1
    [[optimization.constraint]]
        name = "second:constraint"
        lower = -1.5
        upper = 1.0   # TOML format does not accept "1."

    [[optimization.objective]]
        name = "one:objective:function"
```

Here are some problems I saw in relation with current formatting (please feel free:
1. There is a mix of keys that can be named by user (model names, group names) and keys that have fixed names ("model", "design_var", ...)
1. There is a mix of simple and double brackets that is part of TOML syntax, but that can be confusing for users.
1. Nested structures require to repeat the name of parent structure (e.g. **`model`**`.my_first_model`)
1. TOML format does not support floats that end with a dot: `1.0` is Ok, but `1.` is not.

Some modifications of current format could be implemented to fix some of these problems. For instance, even if it is not required by TOML syntax, we could decide that double-bracketed keys have fixed name, whereas simple-bracketed keys are free to name. Also, as design variables, constraints and objective are obviously related to optimization, the "optimization" key might be removed.
That would give:
```toml
title = "Possible alternative to current format"

# List of folder paths where user added custom registered OpenMDAO components
module_folders = ["my/folder", "some/other/folder"]

# Input and output files
input_file = "./problem_inputs.xml"
output_file = "./problem_outputs.xml"

# Definition of problem driver assuming the OpenMDAO convention "import openmdao.api as om"
driver = "om.ScipyOptimizeDriver(tol=1e-6, optimizer='COBYLA')"


# Definition of OpenMDAO model
[[model]]
# Solvers are defined assuming the OpenMDAO convention "import openmdao.api as om"
    nonlinear_solver = "om.NonlinearBlockGS(maxiter=200)"
    linear_solver = "om.DirectSolver()"

    # Although "model" is a mandatory name for the top level of the model, its
    # sub-components can be freely named by user
    [model.my_first_model]
        # An OpenMDAO component is identified by its "id"
        id = "my.first.model"
    [model.my_group]
        [model.my_group.my_second_model]
            id = "my.second.model"
        [model.my_group.my_third_model]
            id = "my.third.model"
            some_model_option = 11


# Optimization settings
[[design_var]]
    name = "first:design_var"
    lower = 0.0
    upper = 42.0
[[design_var]]
    name = "second:design_var"
    lower = -100.0
    upper = 0.0

[[constraint]]
    name = "first:constraint"
    lower = 0.05
    upper = 0.1
[[constraint]]
    name = "second:constraint"
    lower = -1.5
    upper = 1.0

[[objective]]
    name = "one:objective:function"
```

Another way might be to change to YAML, which is also a popular format. Unlike TOML, indentation is part of YAML syntax. A sample file could be:
```yaml
title: YAML alternative
module_folders: [ my/folder, some/other/folder ]

# Input and output files
input_file: ./problem_inputs.xml
output_file: ./problem_outputs.xml

# Definition of problem driver assuming the OpenMDAO convention import openmdao.api as om
driver: om.ScipyOptimizeDriver(tol:1e-6, optimizer:'COBYLA')

# Definition of OpenMDAO model
model_settings:
  # Solvers are defined assuming the OpenMDAO convention import openmdao.api as om
  nonlinear_solver: om.NonlinearBlockGS(maxiter:200)
  linear_solver: om.DirectSolver()

model:
  # Although "model" is a mandatory name for the top level of the model, its
  # sub-components can be freely named by user
  my_first_model:
    id: my.first.model
  my_group:
    my_second_model:
      id: my.second.model
    my_third_model:
      id: my.third.model
      some_model_option: 11


# This section is needed only if optimization process is run
optimization:
  design_vars:
    - name: first:design_var
      lower: 0.0
      upper: 42.0
    - name: second:design_var
      lower: -100.0
      upper: 0.0

  constraints:
    - name: first:constraint
      lower: 0.05
      upper: 0.1
    - name: second:constraint
      lower: -1.5
      upper: 1.

  objective: one:objective:function
```

I like some features of YAML:
- indentation decides what is nested in what --> no need to repeat parent name
- strings do not need to be quoted
- `1.` is accepted

On the other side, I fear that some user may break indentations by accidentally adding/removing some space. (although such problems may be identified at runtime using schema validation...)

What do you think? Any opinion is welcome !

_Originally posted by @christophe-david in https://github.com/fast-aircraft-design/FAST-OAD/discussions/213_
