### ISSUE TITLE
Optimization failed with in-house model

### ISSUE THREAD

**Issue by AleSgueglia** [fast-aircraft-design/FAST-OAD#282]
I developed some in-house models, for the mass and the performance, and despite the evaluation works fine, the optimization fails every time I try to launch it, no matter the tolerance and the starting point. 
Interesting is that if I create my own code for the loop, I have no problem and the optimization, with the same settings, converges fine. 
Attached the configuration file and the error that I obtain. 

[Conf_and_output_issue.zip](https://github.com/fast-aircraft-design/FAST-OAD/files/6182601/Conf_and_output_issue.zip)

**Comment by christophe-david** [comment]
Unfortunately, it is difficult to conclude anything from these outputs.
I would suggest to use all prints that OpenMDAO can provide by modifying your configuration with:
```toml
driver = "om.ScipyOptimizeDriver(tol=1e-6, optimizer='SLSQP', debug_print=['desvars', 'ln_cons', 'nl_cons', 'objs', 'totals'])"
...
nonlinear_solver = "om.NonlinearBlockGS(maxiter=200, iprint=2)"
```
Once this modification is done, I would appreciate that you send obtained outputs from these runs:
- using `fastoad eval`
- using `fastoad optim`
- using `run_driver` on your equivalent OpenMDAO problem with the same settings as above

Hopefully we will see discrepancies that may help understand the problem.
