### ISSUE TITLE
Specify imports or initial code in the configuration file

### ISSUE THREAD

**Issue by ScottDelbecq** [fast-aircraft-design/FAST-OAD#413]
**Is your feature request related to a problem? Please describe.**
It would be nice to specify some imports or piece of code in the configuration file to be executed before the FAST-OAD process. 

**Describe the solution you'd like**
We could imagine something like for example:
```yml
title: Sample OAD Process

# List of folder paths where user added custom registered OpenMDAO components
module_folders:

# Input and output files
input_file: ./problem_inputs.xml
output_file: ./problem_outputs.xml

# Python code to be executed
script: >
    import numpy as np
    from mydriver import MyDriver
    maxiter = np.ceil(2022/3)

# Definition of problem driver
driver: MyDriver(tol=1e-2, optimizer='COBYLA', maxiter=maxiter)

```

**Describe alternatives you've considered**
Of course other key names instead of `script`, like `code`.

**Comment by ScottDelbecq** [comment]
Another need would be to modify the driver options/attributes after instantiation:
```python
prob.driver = om.pyOptSparseDriver(optimizer='SLSQP')

prob.driver.opt_settings['MAXIT'] = 3
```

**Comment by ScottDelbecq** [comment]
For importing additional packages or drivers we could provide the possibility to specify what to import:

```yml
title: Sample OAD Process

# List of folder paths where user added custom registered OpenMDAO components
module_folders:

# Input and output files
input_file: ./problem_inputs.xml
output_file: ./problem_outputs.xml

# Imports
imports:
    - my_driver_1: MyDriver1
    - my_driver_2: MyDriver2

# Definition of problem driver
driver: MyDriver1(tol=1e-2, optimizer='COBYLA', maxiter=maxiter)

```

These imports would be equivalent to:

```python
from my_driver_1 import MyDriver1
from my_driver_2 import MyDriver2
```

**Comment by ScottDelbecq** [comment]
Annoter idea of syntax to allow modification of driver attributes (in particular options):
```yaml

      driver:
        instance: om.ScipyOptimizeDriver()
        opt_settings:
            maxiter: 100
            tol: 1e-2
            optimizer: 'COBYLA'


```
