### ISSUE TITLE
Fichier de configuration FAST

### ISSUE THREAD

**Issue by christophe-david** [fast-aircraft-design/FAST-OAD#43]
J'ouvre une discussion sur la structure et le contenu du fichier de configuration.

L'état actuel est qu'il est écrit en format TOML et peut décrire un problème OpenMDAO en allant chercher tout module préalablement "enregistré", dans FAST ou dans le(s) dossier(s) indiqué(s) par l'utilisateur.

Il est également possible de spécifier des attributs comme le nonlinear_solver, mais c'est fait à travers un eval et est destiné à disparaître. Cela offre pour l'instant une certaine souplesse et permettra de constater ce qui est nécessaire sans avoir forcément à l'implémenter tout de suite.

**Exemple de fichier**

```toml


title = "Sellar"

module_folders = [
  "./custom_modules"
]

input_file = "inputs.xml"
output_file = "outputs.xml"

[problem]
  driver = "om.ScipyOptimizeDriver()"
  [problem.group]
    nonlinear_solver = "om.NonlinearBlockGS(atol=1e-8, rtol=1e-8)"
    [problem.group.disc1]
      id = "sellar.disc1"
    [problem.group.disc2]
      id = "sellar.disc2"
  [problem.functions]
    id = "sellar.functions"

[[design_var]]
  name = "category1/x"
  lower = 0
  upper = 10
[[design_var]]
  name = "category1/z"
  lower = [-10,0]
  upper = 10

[[objective]]
  name = "funcs/f"

[[constraint]]
  name = "funcs/g1"
  upper = 0
[[constraint]]
  name = "funcs/g2"
  upper = 0

```
