### ISSUE TITLE
long computational time for time step simulations ( which increases with the range) .

### ISSUE THREAD

**Issue by aeomath** [fast-aircraft-design/FAST-OAD#541]
**Describe the bug**
For time-step simulations, as the design range increases, it seems that the computation time also increases. (as well as the number of iterations). For example, for a 1500 NM range simulation, the computation time was ~ 3,5 min (and 20 iterations) , while for a 2500 NM range simulation, ~5 min were required. Finally , for a 3500 NM range simulation, 10 min were required ( and 280 iterations).

Only the design range requirement has been changed between the simulations.

The mission example taken for reporting this issue was the default mission  "sizing_mission".
The reference aircraft file taken is the CeRAS

**Comment by christophe-david** [comment]
Thanks for the report.
You mentioned nothing about the configuration file. If it is not a default one, could you please provide it here?

**Comment by aeomath** [comment]
Thanks for your response.

I used the following configuration file (very close to the default one) 
```` 
title: OAD Process Fan

module_folders:

input_file: ../results/oad_process_fan_inputs.xml
output_file: ../results/oad_process_fan_outputs.xml

model:
  aircraft_sizing:
    nonlinear_solver: om.NonlinearBlockGS(maxiter=100, atol=1e-2)
    linear_solver: om.DirectSolver()
    geometry:
      id: fastoad.geometry.legacy
    weight:
      id: fastoad.weight.legacy
    mtow:
      id: fastoad.mass_performances.compute_MTOW
    aerodynamics_highspeed:
      id: fastoad.aerodynamics.highspeed.legacy
    aerodynamics_lowspeed:
      id: fastoad.aerodynamics.lowspeed.legacy
    aerodynamics_takeoff:
      id: fastoad.aerodynamics.takeoff.legacy
    aerodynamics_landing:
      id: fastoad.aerodynamics.landing.legacy
    use_xfoil: false
    performance:
          id: fastoad.performances.mission
          propulsion_id:  fastoad.wrapper.propulsion.rubber_engine
          out_file: ../results/flight_points_fan.csv
          mission_file_path: ::sizing_mission
          adjust_fuel: true
          is_sizing: true
    hq:
      tail_sizing:
        id: fastoad.handling_qualities.tail_sizing
      static_margin:
        id: fastoad.handling_qualities.static_margin
    wing_area:
      id: fastoad.loop.wing_area
      
      ````
