### ISSUE TITLE
OpenMDAO problem from configuration file contains one group per component

### ISSUE THREAD

**Issue by christophe-david** [fast-aircraft-design/FAST-OAD#88]
When the TOML file defines a component with:
``` toml
    [model.my_group.geometry]
        id = "my.geometry.model"
```

The OpenMDAO problem has `model.my_group.geometry` as a Group and `model.my_group.geometry.geometry` as a component. The `geometry` group should not be created.
